[2025-10-15T13:32:25.154+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_project_stop_processes.stop_data_generator manual__2025-10-15T13:32:23.297192+00:00 [queued]>
[2025-10-15T13:32:25.160+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_project_stop_processes.stop_data_generator manual__2025-10-15T13:32:23.297192+00:00 [queued]>
[2025-10-15T13:32:25.160+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-10-15T13:32:25.170+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): stop_data_generator> on 2025-10-15 13:32:23.297192+00:00
[2025-10-15T13:32:25.174+0000] {standard_task_runner.py:60} INFO - Started process 590 to run task
[2025-10-15T13:32:25.177+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pyspark_project_stop_processes', 'stop_data_generator', 'manual__2025-10-15T13:32:23.297192+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_project_stop_processes.py', '--cfg-path', '/tmp/tmplyq84ye1']
[2025-10-15T13:32:25.179+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask stop_data_generator
[2025-10-15T13:32:25.214+0000] {task_command.py:423} INFO - Running <TaskInstance: pyspark_project_stop_processes.stop_data_generator manual__2025-10-15T13:32:23.297192+00:00 [running]> on host 6cb9a48b2a55
[2025-10-15T13:32:25.315+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_project_stop_processes' AIRFLOW_CTX_TASK_ID='stop_data_generator' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T13:32:23.297192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-15T13:32:23.297192+00:00'
[2025-10-15T13:32:25.412+0000] {pyspark_project_stop_processes.py:25} INFO - STDOUT: 
[2025-10-15T13:32:25.413+0000] {pyspark_project_stop_processes.py:26} INFO - STDERR: 
[2025-10-15T13:32:25.414+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2025-10-15T13:32:25.415+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2025-10-15T13:32:25.416+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
[2025-10-15T13:32:25.416+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
[2025-10-15T13:32:25.417+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
[2025-10-15T13:32:25.417+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
[2025-10-15T13:32:25.417+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2025-10-15T13:32:25.418+0000] {logging_mixin.py:188} WARNING - Call stack:
[2025-10-15T13:32:25.443+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2025-10-15T13:32:25.445+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/__main__.py", line 57, in main
    args.func(args)
[2025-10-15T13:32:25.446+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-15T13:32:25.450+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-15T13:32:25.451+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 60, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
[2025-10-15T13:32:25.452+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2025-10-15T13:32:25.453+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 231, in worker
    _run_command_with_daemon_option(
[2025-10-15T13:32:25.454+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 46, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
[2025-10-15T13:32:25.454+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
[2025-10-15T13:32:25.455+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 224, in run_celery_worker
    celery_app.worker_main(options)
[2025-10-15T13:32:25.455+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/base.py", line 389, in worker_main
    self.start(argv=argv)
[2025-10-15T13:32:25.456+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/base.py", line 369, in start
    celery.main(args=argv, standalone_mode=False)
[2025-10-15T13:32:25.456+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2025-10-15T13:32:25.456+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-10-15T13:32:25.456+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-10-15T13:32:25.457+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2025-10-15T13:32:25.457+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-10-15T13:32:25.458+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2025-10-15T13:32:25.459+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2025-10-15T13:32:25.460+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2025-10-15T13:32:25.465+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-10-15T13:32:25.474+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-10-15T13:32:25.479+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2025-10-15T13:32:25.493+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-10-15T13:32:25.494+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-10-15T13:32:25.494+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2025-10-15T13:32:25.495+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2025-10-15T13:32:25.497+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2025-10-15T13:32:25.497+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2025-10-15T13:32:25.498+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2025-10-15T13:32:25.498+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2025-10-15T13:32:25.498+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2025-10-15T13:32:25.499+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2025-10-15T13:32:25.499+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2025-10-15T13:32:25.500+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-10-15T13:32:25.501+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-10-15T13:32:25.502+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-10-15T13:32:25.502+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2025-10-15T13:32:25.503+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2025-10-15T13:32:25.503+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 135, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2025-10-15T13:32:25.503+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 169, in _execute_in_fork
    args.func(args)
[2025-10-15T13:32:25.504+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-15T13:32:25.504+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-15T13:32:25.505+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-10-15T13:32:25.505+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 216, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2025-10-15T13:32:25.505+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 278, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-10-15T13:32:25.506+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2025-10-15T13:32:25.507+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/job.py", line 395, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-10-15T13:32:25.507+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/job.py", line 424, in execute_job
    ret = execute_callable()
[2025-10-15T13:32:25.508+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/local_task_job_runner.py", line 165, in _execute
    self.task_runner.start()
[2025-10-15T13:32:25.508+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/task/task_runner/standard_task_runner.py", line 48, in start
    self.process = self._start_by_fork()
[2025-10-15T13:32:25.509+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/task/task_runner/standard_task_runner.py", line 100, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2025-10-15T13:32:25.509+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-15T13:32:25.510+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-15T13:32:25.510+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-10-15T13:32:25.511+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 218, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2025-10-15T13:32:25.511+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 297, in _run_raw_task
    return ti._run_raw_task(
[2025-10-15T13:32:25.512+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2025-10-15T13:32:25.513+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2025-10-15T13:32:25.513+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2532, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2025-10-15T13:32:25.513+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2549, in _execute_task
    return _execute_task(self, context, task_orig)
[2025-10-15T13:32:25.514+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2025-10-15T13:32:25.514+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2025-10-15T13:32:25.514+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
[2025-10-15T13:32:25.515+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
[2025-10-15T13:32:25.515+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2025-10-15T13:32:25.518+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pyspark_project_stop_processes.py", line 37, in stop_data_generator
    stop_process("data_generator.py")
[2025-10-15T13:32:25.520+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pyspark_project_stop_processes.py", line 27, in stop_process
    log.info("\n\n\n", "Process '{file}' in '{container_name}' container was stopped", "\n\n\n")
[2025-10-15T13:32:25.521+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
[2025-10-15T13:32:25.521+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
[2025-10-15T13:32:25.521+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
[2025-10-15T13:32:25.522+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
[2025-10-15T13:32:25.522+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
[2025-10-15T13:32:25.522+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/log/file_task_handler.py", line 247, in emit
    self.handler.emit(record)
[2025-10-15T13:32:25.523+0000] {logging_mixin.py:188} WARNING - Message: '\n\n\n'
Arguments: ("Process '{file}' in '{container_name}' container was stopped", '\n\n\n')
[2025-10-15T13:32:25.523+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-10-15T13:32:25.541+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pyspark_project_stop_processes, task_id=stop_data_generator, execution_date=20251015T133223, start_date=20251015T133225, end_date=20251015T133225
[2025-10-15T13:32:25.590+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-15T13:32:25.613+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
