[2025-10-19T16:40:41.819+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_project_pipeline.create_topic_sensors_sample manual__2025-10-19T16:39:44.854415+00:00 [queued]>
[2025-10-19T16:40:41.827+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_project_pipeline.create_topic_sensors_sample manual__2025-10-19T16:39:44.854415+00:00 [queued]>
[2025-10-19T16:40:41.828+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-10-19T16:40:41.838+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): create_topic_sensors_sample> on 2025-10-19 16:39:44.854415+00:00
[2025-10-19T16:40:41.844+0000] {standard_task_runner.py:60} INFO - Started process 167 to run task
[2025-10-19T16:40:41.846+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pyspark_project_pipeline', 'create_topic_sensors_sample', 'manual__2025-10-19T16:39:44.854415+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_project_pipeline.py', '--cfg-path', '/tmp/tmpo846scjf']
[2025-10-19T16:40:41.849+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask create_topic_sensors_sample
[2025-10-19T16:40:41.898+0000] {task_command.py:423} INFO - Running <TaskInstance: pyspark_project_pipeline.create_topic_sensors_sample manual__2025-10-19T16:39:44.854415+00:00 [running]> on host 43aa124646d7
[2025-10-19T16:40:41.958+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_project_pipeline' AIRFLOW_CTX_TASK_ID='create_topic_sensors_sample' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T16:39:44.854415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T16:39:44.854415+00:00'
[2025-10-19T16:40:45.264+0000] {pyspark_project_pipeline.py:77} INFO - STDOUT: Created topic sensors-sample.

[2025-10-19T16:40:45.265+0000] {pyspark_project_pipeline.py:78} INFO - STDERR: 
[2025-10-19T16:40:45.265+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2025-10-19T16:40:45.267+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2025-10-19T16:40:45.267+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
[2025-10-19T16:40:45.268+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
[2025-10-19T16:40:45.268+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
[2025-10-19T16:40:45.269+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
[2025-10-19T16:40:45.269+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2025-10-19T16:40:45.269+0000] {logging_mixin.py:188} WARNING - Call stack:
[2025-10-19T16:40:45.282+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2025-10-19T16:40:45.283+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/__main__.py", line 57, in main
    args.func(args)
[2025-10-19T16:40:45.283+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-19T16:40:45.284+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-19T16:40:45.284+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 60, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
[2025-10-19T16:40:45.285+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2025-10-19T16:40:45.285+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 231, in worker
    _run_command_with_daemon_option(
[2025-10-19T16:40:45.286+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 46, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
[2025-10-19T16:40:45.286+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
[2025-10-19T16:40:45.287+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/cli/celery_command.py", line 224, in run_celery_worker
    celery_app.worker_main(options)
[2025-10-19T16:40:45.287+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/base.py", line 389, in worker_main
    self.start(argv=argv)
[2025-10-19T16:40:45.287+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/base.py", line 369, in start
    celery.main(args=argv, standalone_mode=False)
[2025-10-19T16:40:45.288+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2025-10-19T16:40:45.288+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-10-19T16:40:45.289+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-10-19T16:40:45.289+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2025-10-19T16:40:45.290+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-10-19T16:40:45.290+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2025-10-19T16:40:45.291+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2025-10-19T16:40:45.291+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2025-10-19T16:40:45.291+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-10-19T16:40:45.292+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-10-19T16:40:45.292+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2025-10-19T16:40:45.293+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-10-19T16:40:45.293+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-10-19T16:40:45.294+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2025-10-19T16:40:45.294+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2025-10-19T16:40:45.295+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2025-10-19T16:40:45.295+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2025-10-19T16:40:45.295+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2025-10-19T16:40:45.296+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2025-10-19T16:40:45.296+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2025-10-19T16:40:45.297+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2025-10-19T16:40:45.297+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2025-10-19T16:40:45.297+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-10-19T16:40:45.298+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-10-19T16:40:45.298+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-10-19T16:40:45.299+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2025-10-19T16:40:45.299+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2025-10-19T16:40:45.300+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 135, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2025-10-19T16:40:45.300+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 169, in _execute_in_fork
    args.func(args)
[2025-10-19T16:40:45.300+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-19T16:40:45.301+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-19T16:40:45.301+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-10-19T16:40:45.302+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 216, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2025-10-19T16:40:45.302+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 278, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-10-19T16:40:45.302+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2025-10-19T16:40:45.303+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/job.py", line 395, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-10-19T16:40:45.303+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/job.py", line 424, in execute_job
    ret = execute_callable()
[2025-10-19T16:40:45.304+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/jobs/local_task_job_runner.py", line 165, in _execute
    self.task_runner.start()
[2025-10-19T16:40:45.304+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/task/task_runner/standard_task_runner.py", line 48, in start
    self.process = self._start_by_fork()
[2025-10-19T16:40:45.305+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/task/task_runner/standard_task_runner.py", line 100, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2025-10-19T16:40:45.305+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-10-19T16:40:45.306+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2025-10-19T16:40:45.306+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-10-19T16:40:45.306+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 218, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2025-10-19T16:40:45.307+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/cli/commands/task_command.py", line 297, in _run_raw_task
    return ti._run_raw_task(
[2025-10-19T16:40:45.307+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2025-10-19T16:40:45.308+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2025-10-19T16:40:45.308+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2532, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2025-10-19T16:40:45.308+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 2549, in _execute_task
    return _execute_task(self, context, task_orig)
[2025-10-19T16:40:45.309+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2025-10-19T16:40:45.309+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2025-10-19T16:40:45.310+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
[2025-10-19T16:40:45.310+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
[2025-10-19T16:40:45.310+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2025-10-19T16:40:45.311+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pyspark_project_pipeline.py", line 125, in create_topic_sensors_sample
    create_kafka_topic("sensors-sample")
[2025-10-19T16:40:45.311+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pyspark_project_pipeline.py", line 79, in create_kafka_topic
    log.info(f"Topic '{topic_name}' was created!", "="*100, "\n\n")
[2025-10-19T16:40:45.312+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
[2025-10-19T16:40:45.312+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
[2025-10-19T16:40:45.313+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
[2025-10-19T16:40:45.313+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
[2025-10-19T16:40:45.314+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
[2025-10-19T16:40:45.314+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/***/utils/log/file_task_handler.py", line 247, in emit
    self.handler.emit(record)
[2025-10-19T16:40:45.314+0000] {logging_mixin.py:188} WARNING - Message: "Topic 'sensors-sample' was created!"
Arguments: ('====================================================================================================', '\n\n')
[2025-10-19T16:40:45.315+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-10-19T16:40:45.324+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pyspark_project_pipeline, task_id=create_topic_sensors_sample, execution_date=20251019T163944, start_date=20251019T164041, end_date=20251019T164045
[2025-10-19T16:40:45.351+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-19T16:40:45.374+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
